name: U4-S2-NNF
channels:
  - defaults
dependencies:
  - appnope=0.1.0
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cycler=0.10.0
  - decorator=4.4.0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - joblib=0.13.2
  - jupyter_client=5.2.4
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvm-openmp=4.0.1
  - matplotlib=3.1.0
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1c
  - pandas=0.24.2
  - parso=0.5.0
  - patsy=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyparsing=2.4.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - statsmodels=0.10.0
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.33.4
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.22.0
    - h5py==2.9.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - protobuf==3.9.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - werkzeug==0.15.4
    - wrapt==1.11.2
prefix: /Users/jonathansokoll/anaconda3/envs/U4-S2-NNF

